package ru.khozyainov.orderingmealstesttask.ui.search

import ru.khozyainov.orderingmealstesttask.databinding.FragmentSearchBinding
import ru.khozyainov.orderingmealstesttask.utils.ViewBindingFragment

class SearchFragment: ViewBindingFragment<FragmentSearchBinding>(FragmentSearchBinding::inflate)